### ISSUE TITLE
Passing wrong types as Uniforms

### ISSUE THREAD

**Issue by peardox** [jimmckeeth/SkiaSimpleShaderViewer#4]
If you use this as a shader...

```
uniform float3 iImage1Resolution; // iImage1 resolution (pixels)
uniform shader iImage1;          // An input image.


vec4 main( in vec2 fragCoord )
{
    
    // Get the original color of the pixel
    float3 OriginalColor = iImage1.eval(fragCoord).rgb;
    if((fragCoord.x < 0.0) || (fragCoord.y < 0.0)) {
        OriginalColor = float3(0.,0.,0.);
    }
//    if((fragCoord.x > 512) || (fragCoord.y > 512)) { // This line makes it work if uncommented
    if((fragCoord.x > (iImage1Resolution.x)) || (fragCoord.y > (iImage1Resolution.y))) {
        OriginalColor = float3(0.,0.,0.);
    }

	return( float4( OriginalColor, 1.0 ));
}
```
There will be no output but if you uncomment the commented line and comment out the one below it will work.

There is an issue in SkiaSimpleShaderViewer whereby you are passing Integers to something that wants Floats - this affects the creation of the uniforms iImage1Resolution and iResolution

This issue affects any shaders that use a texture - Heartfelt and Playing Marble look distinctly different when correct types are passed
```

**Comment by viniciusfbb** [comment]
Thanks to report the issue! The problem was fixed.

However I opened an issue in Skia4Delphi so that in the next version, an automatic conversion will be added internally in SetUniform whenever possible (as is the case with Integer to Float conversions).
