### ISSUE TITLE
Possibly ignoring alpha?

### ISSUE THREAD

**Issue by peardox** [jimmckeeth/SkiaSimpleShaderViewer#5]
I say 'possibly' as I don't know what colour depth is used for the canvas (if 32 bit then the following should be true)

Using this shader I would usually expect a pure black image but alpha appears to be ignored.

```
uniform float3 iImage1Resolution; // iImage1 resolution (pixels)
uniform shader iImage1;          // An input image.


vec4 main( in vec2 fragCoord )
{
    
    // Get the original color of the pixel
    float3 OriginalColor = iImage1.eval(fragCoord).rgb;

	if(any(greaterThan(fragCoord, iImage1Resolution.xy))) {
        OriginalColor = float3(0.,0.,0.);
    }

	return( float4( OriginalColor, 0.0 )); // <-- Alpha is zero!
}
```

Note : TSkAnimatedPaintBox has an Opacity property that looks to be a bugged as Object Inspector provides a drop-down for "Create New TFloatAnimation" /  "Create New TFloatKeyAnimation" while it appears it should be a Single

**Comment by omonien** [comment]
The opacity property is not Skia’s, but comes with every FMX control. It has nothing to do with the possible Alpha issue you are describing. Opacity gets applied after the component has finished painting, after the Shader’s rendering process that is.

It is a Single, which is a specific Float type. No bug here.

I have no idea about the alpha issue.

**Comment by viniciusfbb** [comment]
Hi!

Probably, this is not an issue. In shader creation, we need to inform if the shader is opaque or not:

https://github.com/skia4delphi/skia4delphi/blob/eed4afbf8a34137a9bfa308bcb5ef87cee84abcb/Source/Skia.pas#L2265

And in the code of this demo, it is passing AOpaque = True:
https://github.com/jimmckeeth/SkiaSimpleShaderViewer/blob/bd34ffba617f660f32eea3836de8ecb25389f397/src/SimpleShaderMain.pas#L145

This parameter was added by Google to apply some optimizations when the shader is opaque. The good news is that in the new versions of Skia (which we have not yet applied to Skia4Delphi) this parameter will no longer exist, as their shader language parser can detect (when creating the shader) whether it is opaque or not automatically:

>   * All of the `makeShader` functions associated with `SkRuntimeEffect` no longer take an
>     `isOpaque` parameter. These functions will now make a best effort to determine if your
>     shader always produces opaque output, and optimize accordingly. If you definitely want your
>     shader to produce opaque output, do so in the shader's SkSL code. This can be done by adjusting
>     any `return` statement in your shader with a swizzle: `return color.rgb1;`.
>     https://review.skia.org/506462

**Comment by peardox** [comment]
> And in the code of this demo, it is passing AOpaque = True:

Ahh - that makes sense as to why I wasn't getting what I was expecting - thx

**Comment by omonien** [comment]
The opacity property is not Skia’s, but comes with every FMX control. It has nothing to do with the possible Alpha issue you are describing. Opacity gets applied after the component has finished painting, after the Shader’s rendering process that is.

It is a Single, which is a specific Float type. No bug here.

--
Grüße / Regards,
Olaf Monien

Sent via iPhone
