### ISSUE TITLE
Update needed for latest Skia4Delphi

### ISSUE THREAD

**Issue by rdobkins** [jimmckeeth/SkiaSimpleShaderViewer#9]
Code won't compile under latest version of Skia4Delphi.  I found the changes for FMX.Skia and System.Skia vice Skia.FMX and just Skia.

Line 137: FEffect.ChildrenShadersByName['iImage1'] := image1.MakeShader(TSKSamplingOptions.High);

The propery ChildrenShadersByName doesn't exist anymore.

**Comment by checkdigits** [comment]
Hi @rdobkins A pull request has been merged which should resolve this. Please reopen this issue if it's still a problem.
